robot_info:
  robot_namespaces: ["waffle_1", "waffle_2", "waffle_3", "waffle_4"]

topics:
  odom: "odom"
  scan: "scan"
  camera: "camera/image_raw"
  cmd_vel: "cmd_vel"
  navigate_to_pose: "navigate_to_pose"
  battery: "battery"
